name: keeping_time_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.1.1
  intl: ^0.17.0
  badges: ^2.0.3
  cached_network_image: ^3.2.0
  dio: ^4.0.6
  flutter_easyloading: ^3.0.5
  intl_phone_number_input: ^0.7.1
  flutter_spinkit: ^5.1.0
  get: ^4.6.1
  flutter_screenutil: ^5.6.0
  google_fonts: ^2.3.0
  shared_preferences: ^2.0.7
  syncfusion_flutter_datepicker: ^20.3.52
  percent_indicator: ^4.2.2
  curved_progress_bar: ^1.0.2
#  qr_code_scanner: ^0.7.0 #1.0.1
  qr_code_scanner: ^1.0.1
  country_pickers: ^2.0.0
  image_picker: ^0.8.4+11
  flutter_datetime_picker: ^1.5.1
  rxdart: ^0.27.3
  jiffy: ^5.0.0
  table_calendar: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^2.1.1
#  flutter_gen_runner:
#  hive_generator: ^1.1.0
  json_serializable: ^4.1.2
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
